# Generated by Django 3.1.2 on 2021-01-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branza', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Branza_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branza_sub', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kraj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kraj', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('wyskosc', models.IntegerField()),
                ('szerokosc', models.IntegerField()),
                ('logo', models.FileField(upload_to='')),
                ('branza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.branza')),
                ('kraj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.kraj')),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.miasto')),
                ('sub_branza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.branza_sub')),
            ],
        ),
    ]
