# Generated by Django 3.1.2 on 2021-02-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='strona',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lista',
            name='logo',
            field=models.ImageField(upload_to='database/logos/'),
        ),
    ]
