# Generated by Django 3.1.2 on 2021-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210201_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='szerokosc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lista',
            name='wyskosc',
            field=models.FloatField(),
        ),
    ]
